# Generated by Django 6.1.1 on 2026-10-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('energy', models.CharField(choices=[('light', 'Leve'), ('medium', 'Média'), ('heavy', 'Pesada')], default='medium', max_length=6)),
                ('status', models.CharField(choices=[('today', 'Hoje'), ('later', 'Para depois'), ('done', 'Concluída')], default='today', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('focus_seconds', models.PositiveIntegerField(default=0)),
                ('focus_started_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('focus_seconds__gte', 0)), name='task_focus_seconds_non_negative'), models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('status', 'done')), models.Q(models.Q(('status', 'done'), _negated=True), ('completed_at__isnull', True)), _connector='OR'), name='task_completed_at_iff_done')],
            },
        ),
    ]
